DATABASE = 'data/cache.sqlite3'
RANGE = {
    'default': { 'demand_type': 'unknown',
                                 'end': 10,
                                 'hazard': 'unknown',
                                 'start': 0.1
    },
    'earthquake-0.1 sec sa': {   'demand_type': '0.1 Sec Sa',
                                 'end': 5,
                                 'hazard': 'earthquake',
                                 'start': 0.1},
    'earthquake-0.2 sec sa': {   'demand_type': '0.2 Sec Sa',
                                 'end': 5,
                                 'hazard': 'earthquake',
                                 'start': 0.1},
    'earthquake-0.3 sec sa': {   'demand_type': '0.3 Sec Sa',
                                 'end': 5,
                                 'hazard': 'earthquake',
                                 'start': 0.1},
    'earthquake-pga': {   'demand_type': 'pga',
                          'end': 2,
                          'hazard': 'earthquake',
                          'start': 0.1},
    'earthquake-pgd': {   'demand_type': 'pgd',
                          'end': 20,
                          'hazard': 'earthquake',
                          'start': 0.1},
    'earthquake-pgv': {   'demand_type': 'pgv',
                          'end': 20,
                          'hazard': 'earthquake',
                          'start': 0.1},
    'earthquake-sd': {   'demand_type': 'sd',
                         'end': 20,
                         'hazard': 'earthquake',
                         'start': 0.1},
    'flood-inundationdepth': {   'demand_type': 'inundationDepth',
                                 'end': 50,
                                 'hazard': 'flood',
                                 'start': 0.1},
    'flood-watersurfaceelevation': {   'demand_type': 'waterSurfaceElevation',
                                       'end': 20,
                                       'hazard': 'flood',
                                       'start': 0.1},
    'hurricane-inundationdepth': {   'demand_type': 'inundationDepth',
                                     'end': 50,
                                     'hazard': 'hurricane',
                                     'start': 0.1},
    'hurricane-inundationduration': {   'demand_type': 'inundationDuration',
                                        'end': 50,
                                        'hazard': 'hurricane',
                                        'start': 0.1},
    'hurricane-surgelevel': {   'demand_type': 'surgeLevel',
                                'end': 50,
                                'hazard': 'hurricane',
                                'start': 0.1},
    'hurricane-watervelocity': {   'demand_type': 'waterVelocity',
                                   'end': 5,
                                   'hazard': 'hurricane',
                                   'start': 0.1},
    'hurricane-wavedirection': {   'demand_type': 'waveDirection',
                                   'end': 10,
                                   'hazard': 'hurricane',
                                   'start': 0.1},
    'hurricane-waveheight': {   'demand_type': 'waveHeight',
                                'end': 50,
                                'hazard': 'hurricane',
                                'start': 0.1},
    'hurricane-waveperiod': {   'demand_type': 'wavePeriod',
                                'end': 25,
                                'hazard': 'hurricane',
                                'start': 0.1},
    'hurricane-windvelocity': {   'demand_type': 'windVelocity',
                                  'end': 250,
                                  'hazard': 'hurricane',
                                  'start': 0.1},
    'hurricanewindfield-3s gust': {   'demand_type': '3s gust',
                                      'end': 200,
                                      'hazard': 'hurricaneWindfield',
                                      'start': 0.1},
    'hurricanewindfield-60s': {   'demand_type': '60s',
                                  'end': 160,
                                  'hazard': 'hurricaneWindfield',
                                  'start': 0.1},
    'tornado-wind': {   'demand_type': 'wind',
                        'end': 250,
                        'hazard': 'tornado',
                        'start': 0.1},
    'tsunami-hmax': {   'demand_type': 'Hmax',
                        'end': 50,
                        'hazard': 'tsunami',
                        'start': 0.1},
    'tsunami-vmax': {   'demand_type': 'Vmax',
                        'end': 50,
                        'hazard': 'tsunami',
                        'start': 0.1}
    }
